### ISSUE TITLE
Writing to RFID tag 

### ISSUE THREAD

**Issue by freak4pc** [bensinober/node_rfidgeek#1]
Hey , 
Great code! 

Two short questions
1. Could I Use this to write info to the RFID tag ? 
2. Was this tested with any other readers other then the Univelop 500 RFID ? 

Thank you very much!
Shai.

**Comment by bensinober** [comment]
Hi Shai,

actually, I started a 'develop' branch, rewriting the code to be more generic, Unfortunately, I got distracted with other work so never got to finish it, but believe it's working partly at least.

> 1. Could I Use this to write info to the RFID tag ? 

the develop branch also adds code to write data to ISO15693 tags, though it's complicated to write async code to perform the sync write to a serial USB port. 

> 1. Was this tested with any other readers other then the Univelop 500 RFID ?

No, but I wrote it to be generic so that any reader should work, providing:
  1) it communicates as a USB serial device (ttyUSBx in linux/OSX)
  2) It works in the line of initialize > register write request > read response 
  3) supports one or more of the protocols ISO15693, ISO14443A/B, TagIT 

I didn't get to stub out a configuration file in the 'develop' branch but it shouldnt be too much work.
Also, some thought was put into abstracting the communication layer into a simple API, seen e.g. in the TCP Socket client: https://github.com/bensinober/node_rfidgeek/blob/develop/tcpclient.js
so that the RFID reader can be controlled easily via TCP Socket or Websocket commands.

Hope I will be able to continue working on this soon.

Regards,
Benjamin
